var classes = [
    {
        "name": "lids\\PHP\\Branches",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 7,
        "volume": 36.5,
        "difficulty": 1.6,
        "effort": 58.39,
        "level": 0.63,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 22.81,
        "number_operators": 5,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 37,
        "loc": 54,
        "lloc": 17,
        "mi": 110.02,
        "mIwoC": 62.09,
        "commentWeight": 47.93,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "lids\\PHP\\",
        "pageRank": 0.52,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "lids\\PHP\\PNG",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "search_imgs_sub_dir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "find_tier",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_weighted_state",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 12,
        "ccnMethodMax": 7,
        "externals": [
            "lids\\PHP\\Branches",
            "lids\\PHP\\Branches"
        ],
        "parents": [],
        "lcom": 1,
        "length": 253,
        "vocabulary": 57,
        "volume": 1475.72,
        "difficulty": 32.14,
        "effort": 47433.89,
        "level": 0.03,
        "bugs": 0.49,
        "time": 2635,
        "intelligentContent": 45.91,
        "number_operators": 73,
        "number_operands": 180,
        "number_operators_unique": 15,
        "number_operands_unique": 42,
        "cloc": 40,
        "loc": 106,
        "lloc": 66,
        "mi": 77.22,
        "mIwoC": 36.51,
        "commentWeight": 40.72,
        "kanDefect": 0.87,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.22,
        "relativeSystemComplexity": 6.22,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 6.67,
        "totalSystemComplexity": 18.67,
        "package": "lids\\PHP\\",
        "pageRank": 0.17,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "lids\\PHP\\Save",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "save_dataset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load_dataset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "lids\\PHP\\Tier",
            "lids\\PHP\\Tier",
            "lids\\PHP\\Tier"
        ],
        "parents": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 8,
        "volume": 75,
        "difficulty": 5.4,
        "effort": 405,
        "level": 0.19,
        "bugs": 0.03,
        "time": 23,
        "intelligentContent": 13.89,
        "number_operators": 7,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 16,
        "loc": 35,
        "lloc": 19,
        "mi": 102.01,
        "mIwoC": 58.71,
        "commentWeight": 43.31,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "lids\\PHP\\",
        "pageRank": 0.1,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "lids\\PHP\\Tier",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insert_branch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add_branch_img",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search_imgs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "label_search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "relabel_img",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 27,
        "ccn": 22,
        "ccnMethodMax": 10,
        "externals": [
            "lids\\PHP\\PNG",
            "lids\\PHP\\Save",
            "lids\\PHP\\Branches",
            "lids\\PHP\\Branches",
            "lids\\PHP\\PNG",
            "lids\\PHP\\Branches",
            "lids\\PHP\\PNG",
            "lids\\PHP\\Branches",
            "lids\\PHP\\Branches",
            "lids\\PHP\\Branches"
        ],
        "parents": [
            "lids\\PHP\\PNG"
        ],
        "lcom": 1,
        "length": 248,
        "vocabulary": 49,
        "volume": 1392.45,
        "difficulty": 23.3,
        "effort": 32447.7,
        "level": 0.04,
        "bugs": 0.46,
        "time": 1803,
        "intelligentContent": 59.75,
        "number_operators": 87,
        "number_operands": 161,
        "number_operators_unique": 11,
        "number_operands_unique": 38,
        "cloc": 59,
        "loc": 164,
        "lloc": 105,
        "mi": 71,
        "mIwoC": 30.94,
        "commentWeight": 40.06,
        "kanDefect": 1.38,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 26.33,
        "totalStructuralComplexity": 150,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 158,
        "package": "lids\\PHP\\",
        "pageRank": 0.22,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    }
]